name: lingo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6

  # firebase

  #core
  curved_navigation_bar: ^1.0.3
  kartal: ^3.1.0

  cupertino_icons: ^1.0.2
  #theme
  flex_color_scheme: ^7.1.2
  google_fonts: ^5.1.0
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  uuid: ^3.0.6
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.6.0
  flutter_slidable: ^3.0.0
  flutter_tts: ^3.7.0
  search_page: ^2.3.0
  mask_text_input_formatter: ^2.5.0
  day_night_switch: ^1.0.4
  stop_watch_timer: ^3.0.1


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  hive_generator: ^2.0.0


 
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/

